#include "codegen.h"
#include <sstream>
#include <algorithm>
#include <cassert>

/* -----------------------------------------------------------------------
 * Infrastructure
 * --------------------------------------------------------------------- */
static std::string indent_str(int n) { return std::string((size_t)n * 4, ' '); }

void Codegen::iout(const std::string& s) {
    out << indent_str(indent) << s << '\n';
}

std::string Codegen::fresh_tmp() {
    return "_t" + std::to_string(tmp_counter++);
}

std::string Codegen::mangle(const std::string& cls, const std::string& fn) const {
    return cls + "_" + fn;
}

/* -----------------------------------------------------------------------
 * C type mapping
 * --------------------------------------------------------------------- */
std::string Codegen::c_type(const TypeRef& t) {
    switch (t.kind) {
        case TypeKind::INT:   return "int64_t";
        case TypeKind::FLOAT: return "double";
        case TypeKind::BOOL:  return "int";
        case TypeKind::VOID:  return "void";
        case TypeKind::STR:   return "GrandaStr*";
        case TypeKind::ARRAY: return "GrandaArray*";
        case TypeKind::CLASS: return t.class_name + "*";
        default:              return "void*";
    }
}

std::string Codegen::c_default(const TypeRef& t) {
    switch (t.kind) {
        case TypeKind::INT:   return "0";
        case TypeKind::FLOAT: return "0.0";
        case TypeKind::BOOL:  return "0";
        default:              return "NULL";
    }
}

bool Codegen::type_is_gc(const TypeRef& t) const {
    return t.kind == TypeKind::STR || t.kind == TypeKind::ARRAY
        || t.kind == TypeKind::CLASS;
}

bool Codegen::class_has_gc_fields(const ClassDecl& cls) const {
    for (auto& f : cls.fields)
        if (type_is_gc(f.type)) return true;
    if (!cls.base_class.empty()) {
        auto it = class_decls.find(cls.base_class);
        if (it != class_decls.end() && class_has_gc_fields(*it->second))
            return true;
    }
    return false;
}

std::string Codegen::bin_op_str(BinOp op, const TypeRef& rt) {
    (void)rt;
    switch (op) {
        case BinOp::ADD: return "+";
        case BinOp::SUB: return "-";
        case BinOp::MUL: return "*";
        case BinOp::DIV: return "/";
        case BinOp::MOD: return "%";
        case BinOp::EQ:  return "==";
        case BinOp::NEQ: return "!=";
        case BinOp::LT:  return "<";
        case BinOp::GT:  return ">";
        case BinOp::LEQ: return "<=";
        case BinOp::GEQ: return ">=";
        case BinOp::AND: return "&&";
        case BinOp::OR:  return "||";
    }
    return "+";
}

/* -----------------------------------------------------------------------
 * Main entry
 * --------------------------------------------------------------------- */
std::string Codegen::emit(const Program& prog) {
    /* Index classes */
    for (auto& cls : prog.classes)
        class_decls[cls.name] = &cls;

    /* --- preamble --- */
    out << "/* Generated by the Granda compiler 0.1.0 */\n";
    out << "#include <stdint.h>\n";
    out << "#include <stdio.h>\n";
    out << "#include <stdlib.h>\n";
    out << "#include <string.h>\n";
    out << "#include \"granda_rt.h\"\n\n";

    /* --- forward declarations for all classes and functions --- */
    for (auto& cls : prog.classes) emit_class_forward(cls);
    out << '\n';

    /* --- class structs + alloc helpers --- */
    for (auto& cls : prog.classes) {
        emit_class_struct(cls);
        emit_class_alloc(cls);
        out << '\n';
    }

    /* --- forward-declare all user functions (so order doesn't matter) --- */
    for (auto& cls : prog.classes)
        for (auto& m : cls.methods)
            emit_fn_decl(m, cls.name);
    for (auto& fn : prog.functions)
        emit_fn_decl(fn);
    out << '\n';

    /* --- function bodies --- */
    for (auto& cls : prog.classes)
        for (auto& m : cls.methods)
            emit_fn_body(m, cls.name);
    for (auto& fn : prog.functions)
        emit_fn_body(fn);

    /* --- C main --- */
    out << "\nint main(void) {\n";
    out << "    gc_init();\n";
    out << "    granda_main();\n";
    out << "    gc_shutdown();\n";
    out << "    return 0;\n";
    out << "}\n";

    return out.str();
}

/* -----------------------------------------------------------------------
 * Class emission
 * --------------------------------------------------------------------- */
void Codegen::emit_class_forward(const ClassDecl& cls) {
    out << "typedef struct " << cls.name << "_s " << cls.name << ";\n";
}

void Codegen::emit_class_struct(const ClassDecl& cls) {
    out << "struct " << cls.name << "_s {\n";
    out << "    GC_Header _gc;\n";
    if (!cls.base_class.empty())
        out << "    /* base fields from " << cls.base_class << " */\n";

    /* Collect all fields including inherited */
    std::vector<const FieldDecl*> all_fields;
    /* First add base fields */
    if (!cls.base_class.empty()) {
        auto it = class_decls.find(cls.base_class);
        if (it != class_decls.end())
            for (auto& f : it->second->fields)
                all_fields.push_back(&f);
    }
    for (auto& f : cls.fields) all_fields.push_back(&f);

    for (auto* f : all_fields)
        out << "    " << c_type(f->type) << " " << f->name << ";\n";

    out << "};\n";
}

void Codegen::emit_class_alloc(const ClassDecl& cls) {
    bool has_gc = class_has_gc_fields(cls);

    /* trace function */
    if (has_gc) {
        out << "static void " << cls.name << "_gc_trace(GC_Header* _h) {\n";
        out << "    " << cls.name << "* self = (" << cls.name << "*)_h;\n";

        /* Trace base class fields too */
        if (!cls.base_class.empty()) {
            auto it = class_decls.find(cls.base_class);
            if (it != class_decls.end())
                for (auto& f : it->second->fields)
                    if (type_is_gc(f.type))
                        out << "    rc_retain(self->" << f.name << ");\n";
        }
        for (auto& f : cls.fields)
            if (type_is_gc(f.type))
                out << "    rc_retain(self->" << f.name << ");\n";
        out << "}\n";
    }

    /* free function */
    out << "static void " << cls.name << "_gc_free(GC_Header* _h) {\n";
    out << "    " << cls.name << "* self = (" << cls.name << "*)_h;\n";

    /* Release base class GC fields */
    if (!cls.base_class.empty()) {
        auto it = class_decls.find(cls.base_class);
        if (it != class_decls.end())
            for (auto& f : it->second->fields)
                if (type_is_gc(f.type))
                    out << "    rc_release(self->" << f.name << ");\n";
    }
    for (auto& f : cls.fields)
        if (type_is_gc(f.type))
            out << "    rc_release(self->" << f.name << ");\n";
    out << "    free(self);\n";
    out << "}\n";

    /* alloc helper */
    out << "static " << cls.name << "* " << cls.name << "_alloc(void) {\n";
    out << "    " << cls.name << "* _obj = (" << cls.name
        << "*)malloc(sizeof(" << cls.name << "));\n";
    out << "    if (!_obj) granda_panic(\"Out of memory allocating "
        << cls.name << "\");\n";
    out << "    memset(_obj, 0, sizeof(" << cls.name << "));\n";
    out << "    _obj->_gc.ref_count = 1;\n";
    out << "    _obj->_gc.type_tag  = GRANDA_TAG_CLASS;\n";
    out << "    _obj->_gc.trace     = "
        << (has_gc ? cls.name + "_gc_trace" : "NULL") << ";\n";
    out << "    _obj->_gc.free_fn   = " << cls.name << "_gc_free;\n";
    out << "    return _obj;\n";
    out << "}\n";
}

/* -----------------------------------------------------------------------
 * Function declaration (forward decl)
 * --------------------------------------------------------------------- */
void Codegen::emit_fn_decl(const FnDecl& fn, const std::string& class_ctx) {
    std::string mangled = class_ctx.empty() ? fn.name : mangle(class_ctx, fn.name);
    /* Rename 'main' → 'granda_main' to avoid conflict with C main */
    if (mangled == "main") mangled = "granda_main";

    out << c_type(fn.return_type) << " " << mangled << "(";
    bool first = true;
    for (auto& p : fn.params) {
        if (!first) out << ", "; first = false;
        if (p.name == "self") {
            out << class_ctx << "* self";
        } else {
            out << c_type(p.type) << " " << p.name;
        }
    }
    if (first) out << "void";
    out << ");\n";
}

/* -----------------------------------------------------------------------
 * Function body
 * --------------------------------------------------------------------- */
void Codegen::emit_fn_body(const FnDecl& fn, const std::string& class_ctx) {
    current_class = class_ctx;
    tmp_counter = 0;

    std::string mangled = class_ctx.empty() ? fn.name : mangle(class_ctx, fn.name);
    if (mangled == "main") mangled = "granda_main";

    out << c_type(fn.return_type) << " " << mangled << "(";
    bool first = true;
    for (auto& p : fn.params) {
        if (!first) out << ", "; first = false;
        if (p.name == "self") {
            out << class_ctx << "* self";
        } else {
            out << c_type(p.type) << " " << p.name;
        }
    }
    if (first) out << "void";
    out << ") {\n";
    indent = 1;
    emit_block(fn.body);
    indent = 0;
    out << "}\n\n";

    current_class = "";
}

/* -----------------------------------------------------------------------
 * Block and statement
 * --------------------------------------------------------------------- */
void Codegen::emit_block(const std::vector<StmtPtr>& stmts) {
    for (auto& s : stmts) emit_stmt(*s);
}

void Codegen::emit_stmt(const Stmt& stmt) {
    switch (stmt.kind) {

    case Stmt::Kind::VarDecl: {
        std::string ct = c_type(stmt.var_type);
        std::string init = stmt.var_init
            ? emit_expr(*stmt.var_init)
            : c_default(stmt.var_type);
        iout(ct + " " + stmt.var_name + " = " + init + ";");
        break;
    }

    case Stmt::Kind::ExprStmt:
        if (stmt.expr) {
            std::string val = emit_expr(*stmt.expr);
            /* Only emit as a statement if it could have side effects */
            if (!val.empty() && val != "0" && val != "NULL")
                iout("(void)(" + val + ");");
        }
        break;

    case Stmt::Kind::If: {
        for (size_t i = 0; i < stmt.if_branches.size(); ++i) {
            const auto& br = stmt.if_branches[i];
            std::string cond = emit_expr(*br.cond);
            if (i == 0) iout("if (" + cond + ") {");
            else        iout("else if (" + cond + ") {");
            ++indent;
            emit_block(br.body);
            --indent;
            iout("}");
        }
        if (!stmt.else_body.empty()) {
            iout("else {");
            ++indent;
            emit_block(stmt.else_body);
            --indent;
            iout("}");
        }
        break;
    }

    case Stmt::Kind::While: {
        std::string cond = emit_expr(*stmt.while_cond);
        iout("while (" + cond + ") {");
        ++indent;
        emit_block(stmt.body);
        --indent;
        iout("}");
        break;
    }

    case Stmt::Kind::For: {
        /* Range: for i in start..end */
        if (stmt.for_iter->kind == Expr::Kind::Range) {
            std::string start = emit_expr(*stmt.for_iter->left);
            std::string end   = emit_expr(*stmt.for_iter->right);
            iout("for (int64_t " + stmt.for_var + " = " + start + "; "
                 + stmt.for_var + " < " + end + "; ++" + stmt.for_var + ") {");
        } else {
            /* Array iteration */
            std::string arr   = emit_expr(*stmt.for_iter);
            std::string idx   = fresh_tmp();
            std::string len   = fresh_tmp();
            TypeRef elem_type(TypeKind::INFERRED);
            if (stmt.for_iter->resolved_type.kind == TypeKind::ARRAY
                && stmt.for_iter->resolved_type.elem)
                elem_type = stmt.for_iter->resolved_type.elem->clone();
            std::string elem_ct = c_type(elem_type);

            iout("{");
            ++indent;
            iout("int64_t " + len + " = granda_array_len(" + arr + ");");
            iout("for (int64_t " + idx + " = 0; " + idx + " < " + len
                 + "; ++" + idx + ") {");
            ++indent;

            /* element access */
            if (elem_type.kind == TypeKind::INT)
                iout(elem_ct + " " + stmt.for_var + " = granda_int_array_get("
                     + arr + ", " + idx + ");");
            else if (elem_type.kind == TypeKind::FLOAT)
                iout(elem_ct + " " + stmt.for_var + " = granda_float_array_get("
                     + arr + ", " + idx + ");");
            else
                iout(elem_ct + " " + stmt.for_var + " = (" + elem_ct
                     + ")granda_array_get(" + arr + ", " + idx + ");");
        }
        emit_block(stmt.body);
        if (stmt.for_iter->kind != Expr::Kind::Range) {
            --indent;
            iout("}"); /* inner for */
            --indent;
            iout("}"); /* outer block */
        } else {
            --indent;
            iout("}");
        }
        break;
    }

    case Stmt::Kind::Return: {
        if (stmt.ret_val) {
            std::string val = emit_expr(*stmt.ret_val);
            iout("return " + val + ";");
        } else {
            iout("return;");
        }
        break;
    }

    case Stmt::Kind::Break:    iout("break;");    break;
    case Stmt::Kind::Continue: iout("continue;"); break;
    }
}

/* -----------------------------------------------------------------------
 * Expression emission
 *
 * Emits any necessary temp-variable statements directly to `out`, then
 * returns the C expression string representing the result.
 * --------------------------------------------------------------------- */
std::string Codegen::emit_expr(const Expr& expr) {
    switch (expr.kind) {

    case Expr::Kind::IntLit:
        return expr.str_val + "LL";

    case Expr::Kind::FloatLit:
        return expr.str_val;

    case Expr::Kind::StrLit: {
        /* Escape the string for C */
        std::string escaped;
        for (char c : expr.str_val) {
            switch (c) {
                case '"':  escaped += "\\\""; break;
                case '\\': escaped += "\\\\"; break;
                case '\n': escaped += "\\n";  break;
                case '\t': escaped += "\\t";  break;
                case '\r': escaped += "\\r";  break;
                default:   escaped += c;      break;
            }
        }
        return "granda_str_literal(\"" + escaped + "\")";
    }

    case Expr::Kind::BoolLit:
        return expr.bool_val ? "1" : "0";

    case Expr::Kind::NullLit:
        return "NULL";

    case Expr::Kind::Ident:
        return expr.str_val;

    case Expr::Kind::SelfExpr:
        return "self";

    case Expr::Kind::Binary: {
        std::string lv = emit_expr(*expr.left);
        std::string rv = emit_expr(*expr.right);
        /* String concatenation */
        if (expr.bin_op == BinOp::ADD &&
            expr.left->resolved_type.kind == TypeKind::STR) {
            return "granda_str_concat(" + lv + ", " + rv + ")";
        }
        /* String equality */
        if ((expr.bin_op == BinOp::EQ || expr.bin_op == BinOp::NEQ) &&
            expr.left->resolved_type.kind == TypeKind::STR) {
            std::string eq = "granda_str_eq(" + lv + ", " + rv + ")";
            return (expr.bin_op == BinOp::NEQ) ? "!" + eq : eq;
        }
        return "(" + lv + " " + bin_op_str(expr.bin_op, expr.resolved_type)
               + " " + rv + ")";
    }

    case Expr::Kind::Unary: {
        std::string ov = emit_expr(*expr.operand);
        if (expr.un_op == UnOp::NEG) return "(-" + ov + ")";
        return "(!" + ov + ")";
    }

    case Expr::Kind::Call: {
        /* Built-in functions */
        const std::string& fn = expr.callee_name;
        if (fn == "print" || fn == "println") {
            std::string arg = emit_expr(*expr.args[0]);
            const TypeRef& at = expr.args[0]->resolved_type;
            std::string tmp = fresh_tmp();
            if (at.kind == TypeKind::STR) {
                iout(indent_str(indent) + (fn == "println"
                    ? "granda_println(" + arg + ");"
                    : "granda_print("   + arg + ");"));
            } else if (at.kind == TypeKind::INT) {
                iout("granda_print_int(" + arg + ");");
                if (fn == "println") iout("putchar('\\n');");
            } else if (at.kind == TypeKind::FLOAT) {
                iout("granda_print_float(" + arg + ");");
                if (fn == "println") iout("putchar('\\n');");
            } else if (at.kind == TypeKind::BOOL) {
                iout("granda_print_bool(" + arg + ");");
                if (fn == "println") iout("putchar('\\n');");
            } else {
                iout("granda_println(granda_str_literal(\"<object>\"));");
            }
            (void)tmp;
            return "";
        }
        if (fn == "len") {
            std::string arg = emit_expr(*expr.args[0]);
            const TypeRef& at = expr.args[0]->resolved_type;
            if (at.kind == TypeKind::STR)   return "granda_str_len(" + arg + ")";
            return "granda_array_len(" + arg + ")";
        }
        if (fn == "str") {
            std::string arg = emit_expr(*expr.args[0]);
            const TypeRef& at = expr.args[0]->resolved_type;
            if (at.kind == TypeKind::INT)   return "granda_int_to_str(" + arg + ")";
            if (at.kind == TypeKind::FLOAT) return "granda_float_to_str(" + arg + ")";
            if (at.kind == TypeKind::BOOL)  return "granda_bool_to_str(" + arg + ")";
            return arg; /* already str */
        }
        if (fn == "int") {
            std::string arg = emit_expr(*expr.args[0]);
            return "(int64_t)(" + arg + ")";
        }
        if (fn == "float") {
            std::string arg = emit_expr(*expr.args[0]);
            return "(double)(" + arg + ")";
        }
        if (fn == "assert") {
            std::string arg = emit_expr(*expr.args[0]);
            iout("if (!(" + arg + ")) granda_panic(\"Assertion failed\");");
            return "";
        }
        if (fn == "push") {
            std::string arr = emit_expr(*expr.args[0]);
            std::string val = emit_expr(*expr.args[1]);
            const TypeRef& et = expr.args[1]->resolved_type;
            if (et.kind == TypeKind::INT)
                iout("granda_int_array_push(" + arr + ", " + val + ");");
            else if (et.kind == TypeKind::FLOAT)
                iout("granda_float_array_push(" + arr + ", " + val + ");");
            else
                iout("granda_array_push(" + arr + ", " + val + ");");
            return "";
        }
        if (fn == "pop") {
            std::string arr = emit_expr(*expr.args[0]);
            /* simplified: just decrement length */
            std::string tmp = fresh_tmp();
            iout("/* pop not fully implemented in v0.1 */ (void)" + arr + ";");
            return "NULL";
        }

        /* User-defined function */
        std::string call = fn + "(";
        for (size_t i = 0; i < expr.args.size(); ++i) {
            if (i) call += ", ";
            call += emit_expr(*expr.args[i]);
        }
        call += ")";
        return call;
    }

    case Expr::Kind::MethodCall: {
        std::string obj = emit_expr(*expr.object);
        std::string cls_name = expr.object->resolved_type.class_name;
        std::string call = mangle(cls_name, expr.method_name) + "(" + obj;
        for (auto& a : expr.args)
            call += ", " + emit_expr(*a);
        call += ")";
        return call;
    }

    case Expr::Kind::StaticCall: {
        std::string call = mangle(expr.class_name, expr.method_name) + "(";
        for (size_t i = 0; i < expr.args.size(); ++i) {
            if (i) call += ", ";
            call += emit_expr(*expr.args[i]);
        }
        call += ")";
        return call;
    }

    case Expr::Kind::FieldAccess: {
        std::string obj = emit_expr(*expr.object);
        return obj + "->" + expr.str_val;
    }

    case Expr::Kind::Index: {
        std::string arr = emit_expr(*expr.left);
        std::string idx = emit_expr(*expr.index);
        const TypeRef& et = expr.resolved_type;
        if (et.kind == TypeKind::INT)
            return "granda_int_array_get(" + arr + ", " + idx + ")";
        if (et.kind == TypeKind::FLOAT)
            return "granda_float_array_get(" + arr + ", " + idx + ")";
        return "(" + c_type(et) + ")granda_array_get(" + arr + ", " + idx + ")";
    }

    case Expr::Kind::Assign: {
        std::string rhs = emit_expr(*expr.right);
        if (expr.left->kind == Expr::Kind::Ident) {
            std::string lhs = expr.left->str_val;
            if (type_is_gc(expr.left->resolved_type))
                return "RC_ASSIGN(" + lhs + ", " + rhs + "), " + lhs;
            return "(" + lhs + " = " + rhs + ")";
        }
        if (expr.left->kind == Expr::Kind::FieldAccess) {
            std::string obj = emit_expr(*expr.left->object);
            std::string fld = expr.left->str_val;
            if (type_is_gc(expr.resolved_type))
                return "RC_ASSIGN(" + obj + "->" + fld + ", " + rhs + "), "
                       + obj + "->" + fld;
            return "(" + obj + "->" + fld + " = " + rhs + ")";
        }
        if (expr.left->kind == Expr::Kind::Index) {
            std::string arr = emit_expr(*expr.left->left);
            std::string idx = emit_expr(*expr.left->index);
            const TypeRef& et = expr.resolved_type;
            if (et.kind == TypeKind::INT)
                return "granda_int_array_set(" + arr + ", " + idx + ", " + rhs + "), " + rhs;
            if (et.kind == TypeKind::FLOAT)
                return "granda_float_array_set(" + arr + ", " + idx + ", " + rhs + "), " + rhs;
            return "granda_array_set(" + arr + ", " + idx + ", " + rhs + "), " + rhs;
        }
        return "(/* assign */ " + rhs + ")";
    }

    case Expr::Kind::CompAssign: {
        std::string rhs = emit_expr(*expr.right);
        if (expr.left->kind == Expr::Kind::Ident) {
            std::string lhs = expr.left->str_val;
            std::string op  = bin_op_str(expr.comp_op, expr.resolved_type);
            return "(" + lhs + " " + op + "= " + rhs + ")";
        }
        return "0";
    }

    case Expr::Kind::ArrayLit: {
        if (expr.elements.empty())
            return "granda_array_new(0, 0)";

        const TypeRef& et = expr.resolved_type.elem
            ? *expr.resolved_type.elem : TypeRef(TypeKind::INFERRED);

        std::string tmp = fresh_tmp();
        std::string ct  = c_type(TypeRef::array_of(et.clone()));
        int is_gc = type_is_gc(et) ? 1 : 0;

        if (et.kind == TypeKind::INT) {
            iout(ct + " " + tmp + " = granda_int_array_new("
                 + std::to_string(expr.elements.size()) + ");");
            for (auto& elem : expr.elements) {
                std::string ev = emit_expr(*elem);
                iout("granda_int_array_push(" + tmp + ", " + ev + ");");
            }
        } else if (et.kind == TypeKind::FLOAT) {
            iout(ct + " " + tmp + " = granda_float_array_new("
                 + std::to_string(expr.elements.size()) + ");");
            for (auto& elem : expr.elements) {
                std::string ev = emit_expr(*elem);
                iout("granda_float_array_push(" + tmp + ", " + ev + ");");
            }
        } else {
            iout(ct + " " + tmp + " = granda_array_new("
                 + std::to_string(expr.elements.size()) + ", "
                 + std::to_string(is_gc) + ");");
            for (auto& elem : expr.elements) {
                std::string ev = emit_expr(*elem);
                iout("granda_array_push(" + tmp + ", (void*)" + ev + ");");
            }
        }
        return tmp;
    }

    case Expr::Kind::ClassCons: {
        std::string tmp = fresh_tmp();
        iout(expr.class_name + "* " + tmp + " = " + expr.class_name + "_alloc();");
        for (auto& fi : expr.field_inits) {
            std::string val = emit_expr(*fi.value);
            if (type_is_gc(fi.value->resolved_type))
                iout("RC_ASSIGN(" + tmp + "->" + fi.name + ", " + val + ");");
            else
                iout(tmp + "->" + fi.name + " = " + val + ";");
        }
        return tmp;
    }

    case Expr::Kind::Range:
        /* Range is only consumed by for-loops; if used elsewhere return 0 */
        return "0";
    }

    return "0";
}
